### ISSUE TITLE
[Suggestion] CreateProcessWithBuffer

### ISSUE THREAD

**Issue by Unc3nZureD** [nektra/Deviare-InProc#10]
Another nice feature would be to be able to Create a new Process with an injected DLL which is already read from the disk or downloaded from the internet.

So, eg. If I downloaded a DLL from XY website, but I don't want to write it to disk before Injecting, then I could just call this API and inject it from buffer.

I'm not sure how your Dll injection works (could you explain quickly? LoadLibrary, LdrLoadDll, Manual mapping, etc), but I'm sure it would require some kind of Manual mapping method. It would be great to see such a feature :)

(I'm not yet familiar with GitHub, so I'm not sure if I'm writing to to wrong place, actually I couldn't find any better place. Did I miss anything?)

**Comment by mxmauro** [comment]
Hi,

Deviare is a hooking library and contains some helper routines to assist the developer in several tasks but downloading a file from the web is outside the scope of the library.

If you need to develop a product and/or consulting, feel free to contact [Nektra](http://www.nektra.com/contact/).

Regards.

**Comment by Unc3nZureD** [comment]
Sure I didn't mean to download a file, that's my task. I meant to inject a DLL which is loaded into a buffer (A simply byte/char array)

**Comment by mxmauro** [comment]
We have a propietary LoadDllFromMemory code but currently there is no plan to make it public. MIght be in the future.

**Comment by gitlsl** [comment]
@mxmauro hi， I downloaded source but couldn't compile success， can you release a new version to nuget since it had many update commits

**Comment by scnale** [comment]
@gitlsl Hi, please open a separate issue and provide us with the following details: steps used to perform the build (e.g. run build.bat or build one of the provided solutions), toolkit version used (e.g. VS2015 with update 3), build output and host OS where the build is performed. Also, please answer the following: did you follow the instructions in the readme when cloning the repository or were you using one of the release source packages? We haven't yet looked into the option of releasing a Nuget package.
