### ISSUE TITLE
_CrtIsValidHeapPointer(block)

### ISSUE THREAD

**Issue by besoeso** [nektra/Deviare-InProc#12]
Hi, i have compiled the last code source from Git. 

I have tested the new updates for injection. I use visual studio 2015.

In release mode work fine. This error is for NktHookLibHelpers::CreateProcessWithDllW API.

I have compiled the sample code in debug mode for x32. When try do injection got the follow error:

---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Assertion Failed!

Program: C:\InjectDll.exe
File: minkernel\crts\ucrt\src\appcrt\heap\debug_heap.cpp
Line: 888

Expression: _CrtIsValidHeapPointer(block)

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)

Regards.

**Comment by mxmauro** [comment]
Mmm we didn't get any assertion on our tests. How does the InjectDll sample work in your environment?

**Comment by besoeso** [comment]
It is Windows 7 x32 with Visual studio 2015.

Regards.

**Comment by mxmauro** [comment]
InjectDll provided sample fails with same error?

**Comment by besoeso** [comment]
Yes. I use the sample project injector.

Regards.

**Comment by mxmauro** [comment]
Hi @besoeso we didn't hit any assert on provided InjectDll code but we fixed some issues in dll loader on  injected process. Please try with the uploaded changes.

**Comment by besoeso** [comment]
Hi, i have tested the last changes. All working fine now.  Debug Assertion fixed (no show). 

Thanks and regards.

**Comment by mxmauro** [comment]
Glad to hear! Regards.
