### ISSUE TITLE
build.bat issue

### ISSUE THREAD

**Issue by Unc3nZureD** [nektra/Deviare-InProc#18]
Build.bat doesn't include rules for building vs 2017.

**Comment by Helios-vmg** [comment]
If I remember correctly, since VS2017 vcvarsall.bat is no longer available.
To build from the command line, just start the Visual Studio command prompt and run
`devenv "NktHookLib_2017.sln" /rebuild "<configuration>"`
"<configuration>" may be, for example, "Release|x64".
