### ISSUE TITLE
How to hook .NET methods in remote process?

### ISSUE THREAD

**Issue by Keptark** [nektra/Deviare-InProc#19]
Hi, I would like to hook certain methods in a .NET executable while it is running. I found this sample code:

`object o = cHook.Hook(typeof(SampleClass), "Call", new Type[] { typeof(string), typeof(string) },
typeof(MySampleClass), "Call", new Type[] { typeof(string), typeof(string) });`

But this of course only works inside the current executable, is it possible to achieve the same thing in a remote process using Deviare In-Proc? I know it can also inject DLL's, but as far as I can see, that will only work with a native DLL, and I'd first just like to know if I can do this with C# instead.

**Comment by Helios-vmg** [comment]
You can add native entry points to a managed DLLs, which would it to be loaded by LoadLibrary(), and thus be injected into a remote process.

**Comment by Keptark** [comment]
Thank you! I managed to get a managed DLL injected and working.
But when hooking a method in a certain class, does it has to be 'public' for it to work, or will private/internal access-modifiers work too?
Right now the hooking code above crashes the process for some reason :/

**Comment by Keptark** [comment]
Seems like the crash occurs when initializing the HookLib class in my DLL:

`public static class Program
{
    private static HookLib hookLib;

    static Program()
    {
        hookLib = new HookLib();
     }
}`

Do you know what could go wrong here?

**Comment by lxm470** [comment]
Is it possible that managed DLL loaded by LoadLibrary() and unloaded by FreeLibrary() without crash?

**Comment by mxmauro** [comment]
Resources in .NET are managed by the GC. If you unload the library, it would leak and lead to crashes.

**Comment by DonetCracker** [comment]
> Thank you! I managed to get a managed DLL injected and working.
> But when hooking a method in a certain class, does it has to be 'public' for it to work, or will private/internal access-modifiers work too?
> Right now the hooking code above crashes the process for some reason :/

Could you show your solution?
