### ISSUE TITLE
In-Proc does not fix relative jumps in trampoline functions

### ISSUE THREAD

**Issue by bo3b** [nektra/Deviare-InProc#22]
Please see:
https://github.com/bo3b/3Dmigoto/issues/87

In this specific case, the JNE instruction is moved into the stub, and is not fixed there, which means it's a relative jne to nowhere.

Tested in top-of-tree, and bug still exists.

**Comment by mxmauro** [comment]
Hi @bo3b and @DarkStarSword, I've implemented the changes. Currently testing. I'll use this issue to notify about changes.

**Comment by mxmauro** [comment]
Uploaded changes. Please let me know if they work for you.

**Comment by DarkStarSword** [comment]
Excellent - I've tested the VSSetSamplers case and can confirm this is working for me :)

I'll do some more smoke screen testing on the other hooks, but I think this is resolved and we can close the bug - thanks :)

**Comment by bo3b** [comment]
Yes, looking good.  

Thanks very much for the quick response.

**Comment by mxmauro** [comment]
Excellent guys. When you feel this is over, please close the issue, else let me know.

Kind regards.
