### ISSUE TITLE
Unsafe hooks, lpOriginal is not set right after resuming threads

### ISSUE THREAD

**Issue by prsyahmi** [nektra/Deviare-InProc#8]
Here's the problem, when we call Hook(), the function calls RemoteHook() which then build the trampoline, suspend the threads and do the actual hooking. Once hooked, all the threads is resumed and one of the threads which calls the hooked functions will crash if the detoured function try to call lpOriginal function too, before the Hook() actually return and give proper lpOriginal address.

Let me illustrate a bit:
```
Thread 1 -------------------------- Thread 2
Hook(&lpOriginal) -----------------
RemoteHook() ----------------------
SuspendThreads() ------------------ Suspended
ActualHooking ---------------------
ResumeThreads() ------------------- Running
----------------------------------- Call hooked function
----------------------------------- Call original function (lpOriginal)
----------------------------------- crash due to lpOriginal not set yet
RemoteHook() return ---------------
Hook() return with lpOriginal set -
```

**Comment by mxmauro** [comment]
Hi Syahmi,

Are you trying to hook a function used by Deviare when it is hooking? Or the call is done by another thread after resuming them but before the Hook method return?

Regards,
Mauro.

**Comment by prsyahmi** [comment]
I think the call is done by another thread after resuming them but before the Hook method return if I understand you correctly.

I will show pesudo code example to illustrate the problem better.

```
void* lpCalculateRealtimeOrig = nullptr;

int CalculateRealtime()
{
    return 1;
}

int MyCalculateRealtime()
{
     return lpCalculateRealtimeOrig();
}

DWORD WINAPI Thread2(LPVOID)
{
   for (;;) {
       CalculateRealtime();
   }
}

int main()
{
    CNktHookLib hook;
    CreateThread(Thread2);

    // The hooking by default pauses all other threads leaving only current thread running
    hook.Hook(&idCalcRt, (LPVOID*)&lpCalculateRealtimeOrig, CalculateRealtime, MyCalculateRealtime);
    // Once the hooking is done, it resumes all other threads...
    // However, the calls above isn't returned yet. So the lpCalculateRealtimeOrig is/might still null while the thread 2 already run.
}

```

Above illustrate the problem better, what should be done for safe hooking is the lplpCallOriginal is set right before hooking on this line: https://github.com/nektra/Deviare-InProc/blob/master/Src/Lib/NktHookLib.cpp#L662 instead of passing the value and assign it later after hooking is done and threads resumed here: https://github.com/nektra/Deviare-InProc/blob/master/Src/Lib/NktHookLib.cpp#L152

**Comment by mxmauro** [comment]
Hi Syahmi,

Thanks for the hint. I will apply the change on next working day.

Regards.

**Comment by mxmauro** [comment]
Hi Syahmi,

After checking the code, you can call the `Hook` method that uses the `HOOK_INFO` parameter. The fields are filled before actual hooking occurs. In the other `Hook` method, fields are copied from a temporary `HOOK_INFO` variable to destination.

Regards,
Mauro.

**Comment by prsyahmi** [comment]
Hi Mauro,

I think I will propose a fix for this problem. Stay tune.

**Comment by mxmauro** [comment]
Hi Syahmi,

I uploaded a fix (among other for low IL processes). Please try it.

Regards.

**Comment by prsyahmi** [comment]
Hi Mauro,

Sorry I couldn't get back to you earlier. The commit should fix the problem. Thanks.
