### ISSUE TITLE
Cannot build NtkHookLib from vs2010 solution

### ISSUE THREAD

**Issue by satnatantas** [nektra/Deviare-InProc#9]
`1>..\Lib\libudis86\amalgamation.c(33): fatal error C1083: Cannot open include file: 'source\libudis86\decode.h': No such file or directory`

Using VS2010.

**Comment by mxmauro** [comment]
Hi

You have to clone the repository including submodules.

**Comment by satnatantas** [comment]
Cloned, same issue.

**Comment by mxmauro** [comment]
If submodules were downloaded correctly you must see a folder named "libudis86" inside "Src/Lib/libudis86/source" and the decode.h file there.

**Comment by satnatantas** [comment]
You are completely right. Git does not say anything about recursive cloning on the page about cloning.

Built fine.

**Comment by mxmauro** [comment]
Excellent :)
